"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckCircle2, HelpCircle, History, Loader2, Mic, Send, Sparkles, Trash2, XCircle } from "lucide-react";
import { processAiCommand, type ActiveSessionContext, type AiCommandResult, type ConversationMessage } from "@/app/actions/ai";
import { confirmAiPayment } from "@/app/actions/ai-payment";
import { processAiPreflight } from "@/app/actions/ai-preflight";
import { deleteSessionAction } from "@/app/actions/sessions";
import { deleteStudent } from "@/app/actions/students";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/components/ui/toast";

const samples = ["Aahan was present today", "Aahan paid ₹2,000 for August", "Add homework to today's Aahan class", "Move Aahan permanently to Friday at 5 PM", "Archive Aahan"];
type SpeechRecognitionCtor = new () => { lang: string; start: () => void; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onerror: (() => void) | null };

export default function CommandBar({ minimal = false }: { minimal?: boolean }) {
  const router = useRouter(); const { toast } = useToast(); const [prompt, setPrompt] = useState(""); const [pending, startTransition] = useTransition(); const [result, setResult] = useState<AiCommandResult | null>(null); const [history, setHistory] = useState<ConversationMessage[]>([]); const [activeContext, setActiveContext] = useState<ActiveSessionContext | null>(null); const [recent, setRecent] = useState<string[]>([]); const [deleteStudentState, setDeleteStudentState] = useState<{ id: string; name: string } | null>(null); const [typed, setTyped] = useState("");
  const run = (value: string) => { const text = value.trim(); if (!text || pending) return; const nextHistory = [...history, { role: "user" as const, content: text }]; startTransition(async () => { const preflight = await processAiPreflight(text); if (preflight.handled) { const res: AiCommandResult = { ok: Boolean(preflight.ok), state: preflight.ok ? "RESOLVED" : "NEEDS_CLARIFICATION", message: preflight.message ?? "", activeContext }; setResult(res); setHistory([...nextHistory, { role: "assistant", content: res.message }]); if (res.ok) { setRecent((items) => [text, ...items.filter((x) => x !== text)].slice(0, 5)); toast({ title: "TutorLedger updated", variant: "success" }); router.refresh(); } return; } const res = await processAiCommand(text, nextHistory, activeContext); setResult(res); if (res.activeContext !== undefined) setActiveContext(res.activeContext); setHistory([...nextHistory, { role: "assistant", content: res.message }]); if (res.state === "RESOLVED" && res.ok) { setRecent((items) => [text, ...items.filter((x) => x !== text)].slice(0, 5)); toast({ title: "AI command executed", variant: "success" }); router.refresh(); } }); };
  const submit = (e?: React.FormEvent) => { e?.preventDefault(); const value = prompt; setPrompt(""); run(value); };
  const voice = () => { const Ctor = (window as Window & { SpeechRecognition?: SpeechRecognitionCtor; webkitSpeechRecognition?: SpeechRecognitionCtor }).SpeechRecognition ?? (window as Window & { webkitSpeechRecognition?: SpeechRecognitionCtor }).webkitSpeechRecognition; if (!Ctor) { toast({ title: "Voice input unavailable", description: "Use your phone's keyboard microphone or Safari dictation.", variant: "error" }); return; } const recognition = new Ctor(); recognition.lang = "en-IN"; recognition.onresult = (event) => setPrompt(event.results[0]?.[0]?.transcript ?? ""); recognition.onerror = () => toast({ title: "Voice input failed", variant: "error" }); recognition.start(); };
  const confirmPayment = () => { if (!result?.data) return; const originalPrompt = history.at(-2)?.content ?? ""; startTransition(async () => { const res = await confirmAiPayment(result.data!, originalPrompt); if (!res.ok) { toast({ title: "Payment not recorded", description: res.error, variant: "error" }); return; } toast({ title: "Payment recorded", variant: "success" }); setResult({ ok: true, state: "RESOLVED", message: "Payment recorded with its tuition coverage.", activeContext }); router.refresh(); }); };
  const confirmDeleteSession = () => { const id = String(result?.data?.sessionId ?? ""); if (!id) return; startTransition(async () => { const res = await deleteSessionAction(id); if (!res.ok) { toast({ title: "Class deletion failed", description: res.error, variant: "error" }); return; } setResult({ ok: true, state: "RESOLVED", message: "Class deleted; recurring schedule preserved.", activeContext: null }); router.refresh(); }); };
  const confirmDeleteStudent = () => { if (!deleteStudentState) return; startTransition(async () => { const res = await deleteStudent(deleteStudentState.id, typed); if (!res.ok) { toast({ title: "Student deletion failed", description: res.error, variant: "error" }); return; } setDeleteStudentState(null); setTyped(""); setResult({ ok: true, state: "RESOLVED", message: "Student permanently deleted.", activeContext: null }); router.refresh(); }); };
  return <div className={`w-full ${minimal ? "mx-auto max-w-4xl" : "mt-6 mb-8 space-y-4"}`}>
    <form onSubmit={submit} className={`relative flex items-center ${minimal ? "rounded-[28px] p-[1px] bg-gradient-to-r from-blue-500/20 via-violet-500/25 to-cyan-500/10 shadow-[0_0_70px_rgba(70,90,255,0.07)]" : ""}`}><Sparkles className="pointer-events-none absolute left-4 size-5 text-primary" /><input value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="Ask TutorLedger to record, edit, schedule, check or update anything…" className={`w-full ${minimal ? "rounded-[27px] border-white/8 bg-[#0a0b10] py-5 pl-14 pr-24 text-base" : "rounded-2xl border border-input bg-card py-4 pl-12 pr-24 text-sm"} text-foreground outline-none transition placeholder:text-muted-foreground focus:border-primary/40 focus:ring-2 focus:ring-ring/20`} /><div className="absolute right-2 flex items-center gap-1"><Button type="button" size="icon" variant="ghost" aria-label="Voice command" onClick={voice} className="size-9 rounded-xl"><Mic className="size-4" /></Button><Button type="submit" disabled={pending || !prompt.trim()} size="icon" aria-label="Send command" className="size-9 rounded-xl">{pending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}</Button></div></form>
    {!minimal && <><div className="flex flex-wrap gap-2 text-xs"><span className="py-2 font-medium text-muted-foreground">Try:</span>{samples.map((s) => <button key={s} type="button" onClick={() => setPrompt(s)} className="rounded-lg border border-border/60 bg-muted/40 px-2.5 py-1.5 text-muted-foreground hover:bg-primary/10 hover:text-primary">{s}</button>)}{activeContext?.studentName && <button type="button" onClick={() => setActiveContext(null)} className="rounded-lg border border-primary/20 bg-primary/10 px-2.5 py-1.5 text-primary">Context: {activeContext.studentName} ×</button>}</div>{recent.length > 0 && <div className="rounded-xl border border-border/50 bg-card/40 p-3"><p className="mb-2 flex items-center gap-1.5 text-xs font-semibold"><History className="size-3.5 text-primary" />Recent commands</p><div className="flex flex-wrap gap-2">{recent.map((s) => <button key={s} type="button" onClick={() => run(s)} className="max-w-full truncate rounded-lg border border-border/40 px-2 py-1 text-xs text-muted-foreground hover:text-foreground">{s}</button>)}</div></div>}</>}
    {result && !pending && <Card className={`border ${result.state === "RESOLVED" ? "border-success/30 bg-success/5" : result.state === "NEEDS_CLARIFICATION" ? "border-primary/30 bg-primary/5" : result.state?.includes("CONFIRM") ? "border-warning/30 bg-warning/5" : "border-destructive/30 bg-destructive/5"}`}><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div className="flex gap-2.5">{result.state === "RESOLVED" ? <CheckCircle2 className="mt-0.5 size-5 text-success" /> : result.state === "NEEDS_CLARIFICATION" ? <HelpCircle className="mt-0.5 size-5 text-primary" /> : result.state?.includes("CONFIRM") ? <AlertTriangle className="mt-0.5 size-5 text-warning" /> : <XCircle className="mt-0.5 size-5 text-destructive" />}<div><Badge variant="outline" className="text-[10px] uppercase">{result.state ?? "Notice"}</Badge><p className="mt-1.5 text-sm font-medium leading-relaxed">{result.message}</p></div></div><Button variant="ghost" size="sm" onClick={() => setResult(null)}>Dismiss</Button></div>
      {result.requiresClarification && result.clarificationOptions?.length ? <div className="flex flex-wrap gap-2 border-t border-border/40 pt-3">{result.clarificationOptions.map((o) => <Button key={o} size="sm" variant="outline" onClick={() => run(`${history.at(-2)?.content ?? ""} ${o}`)}>{o}</Button>)}</div> : null}
      {result.requiresConfirmation && result.confirmationPayload ? <div className="flex flex-col justify-between gap-3 rounded-xl border border-warning/30 bg-warning/10 p-3 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold text-warning">{result.confirmationPayload.studentName}</p><p className="text-xs text-muted-foreground">{result.confirmationPayload.details}</p></div><div className="flex gap-2">{result.confirmationPayload.action === "CONFIRM_DELETE_SESSION" ? <Button size="sm" variant="destructive" onClick={confirmDeleteSession}>Delete class</Button> : result.confirmationPayload.action === "CONFIRM_DELETE_STUDENT" ? <Button size="sm" variant="destructive" onClick={() => setDeleteStudentState({ id: result.confirmationPayload!.studentId!, name: result.confirmationPayload!.studentName! })}>Confirm deletion…</Button> : <Button size="sm" onClick={confirmPayment}>Confirm payment</Button>}</div></div> : null}
    </CardContent></Card>}
    {deleteStudentState && <Dialog open onOpenChange={(open) => { if (!open) setDeleteStudentState(null); }}><DialogContent className="max-w-md bg-surface"><DialogHeader><DialogTitle className="flex items-center gap-2 text-destructive"><Trash2 className="size-5" />Permanent student deletion</DialogTitle><DialogDescription>Type <strong>DELETE {deleteStudentState.name.toUpperCase()}</strong> to continue.</DialogDescription></DialogHeader><input value={typed} onChange={(e) => setTyped(e.target.value)} className="h-11 rounded-xl border border-input bg-card px-3 text-sm" placeholder={`DELETE ${deleteStudentState.name.toUpperCase()}`} /><Button disabled={typed.trim().toUpperCase() !== `DELETE ${deleteStudentState.name.toUpperCase()}` || pending} variant="destructive" onClick={confirmDeleteStudent}>{pending ? "Deleting…" : "Permanently delete"}</Button></DialogContent></Dialog>}
  </div>;
}
